# Generated by Django 5.0.14 on 2025-09-11 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
        ("collab", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("file", "File"),
                            ("kb", "Knowledge Base"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pointer",
                    models.TextField(help_text="URL, file path, or KB identifier"),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bots",
                    models.ManyToManyField(
                        related_name="sources", through="bots.BotSource", to="bots.bot"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="collab.channel",
                    ),
                ),
            ],
        ),
    ]
