# Generated by Django 5.0.14 on 2025-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether bot conversations are active in this channel'),
        ),
    ]
