# Generated by Django 5.0.14 on 2025-09-28 12:33

import collab.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_channel_waiting_for_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('details', models.TextField(blank=True, verbose_name='Detaylar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='channels', to='collab.project', verbose_name='İlişkili Projeler'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Asset Adı')),
                ('asset_type', models.CharField(choices=[('document', 'Doküman'), ('image', 'Görsel/Logo'), ('brochure', 'Broşür'), ('reference', 'Referans Link'), ('analysis', 'Analiz Dokümanı'), ('other', 'Diğer')], max_length=20, verbose_name='Asset Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('summary', models.TextField(blank=True, verbose_name="Özet (Bot'lar için)")),
                ('file', models.FileField(blank=True, null=True, upload_to=collab.models.project_asset_upload_path, verbose_name='Dosya')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Tipi')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dosya Boyutu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='collab.project', verbose_name='Proje')),
            ],
            options={
                'verbose_name': "Proje Asset'i",
                'verbose_name_plural': "Proje Asset'leri",
                'ordering': ['-created_at'],
            },
        ),
    ]
