# Generated by Django 5.0.14 on 2025-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_project_channel_projects_projectasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelbot',
            name='is_decision_maker',
            field=models.BooleanField(default=False, verbose_name='Karar Verici'),
        ),
    ]
