# Generated by Django 5.0.14 on 2025-09-11 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("persona_json", models.JSONField(default=dict)),
                ("llm_provider", models.CharField(max_length=100)),
                ("llm_model", models.CharField(max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("system_prompt", models.TextField(blank=True)),
                ("background", models.TextField(blank=True)),
                ("expertise_tags", models.JSONField(default=list)),
                (
                    "stance_profile",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("neutral", "Neutral"),
                            ("critical", "Critical"),
                            ("devils_advocate", "Devil's Advocate"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BotSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bots.bot"
                    ),
                ),
            ],
        ),
    ]
