# Generated by Django 5.0.14 on 2025-09-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bots", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsource",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sources.source"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="botsource",
            unique_together={("bot", "source")},
        ),
    ]
