# Generated by Django 5.0.14 on 2025-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='character',
            field=models.TextField(blank=True, help_text="Bot's personality, background, and communication style"),
        ),
        migrations.AddField(
            model_name='bot',
            name='job_description',
            field=models.TextField(blank=True, help_text="Bot's professional role, expertise, and responsibilities"),
        ),
    ]
