# Generated by Django 5.0.14 on 2025-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot_character_bot_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code for bot avatar', max_length=7),
        ),
    ]
